### ISSUE TITLE
What do we keep / what do we drop?

### ISSUE THREAD

**Issue by jamesturk** [openstates/planning#2]
What's there:

Data:
- bill scrapers
- person scrapers
- vote scrapers
- districts
- committee scrapers (lower priority)
- event scrapers (lower priority)

Other/Data Quality Enhancements:
- bill action categorization
- bill subject categorization
- person deduplication
- <strike>newsblogs </strike>
- <strike>user favoriting</strike>
- <strike>emailing</strike>

Site:
- Cross-state search
- Bill List / Detail
- Person List / Detail
- Who's My Rep?
- Committee List / Detail
- District Maps
- API
- <strike>Full Text Search</strike>

**Comment by jamesturk** [comment]
Initial thoughts:

Top Priorities:
* bill scrapers
* person scrapers
* vote scrapers
* districts
* full text search
* API

Hopefully:
* Entire website

Maybe Nots:
* categorization
* events
* committees

**Comment by jamesturk** [comment]
I think we should have that flat file for sure. & other CSV dumps I'll put into the 'maybe later' pile- I'd rather wait and have people ask for them so we can discuss use cases

**Comment by mileswwatkins** [comment]
Update based on feedback that @jamesturk and I have seen: committee scraping should be at least a "hopefully," and I'm still behind the CSV dumping (we've got at least one request recently for contact info dumps, beyond the old requests).

**Comment by showerst** [comment]
I think we should keep action categorization, it enables some really useful analysis, and most of the states have decent code for it already.

I'd also like to +1 keeping the event scrapers, even if they're lower priority than bills/legs. I'd help maintain them.

The leg data dump is a great idea.

**Comment by mileswwatkins** [comment]
We're also moving committees out of "maybe nots," right? @jamesturk, can you update the list to how things currently stand, for viewers' reference?

**Comment by jamesturk** [comment]
closing this one out as it is sort of obsolete, I updated the initial ticket w/ where things stand.  a fuller prioritization conversation will come as we migrate, but due to outcry/offers of support we won't drop comms/events.   

we did drop:
* full text (just for now)
* email (revisit?)
* newsblogs (for good?)
* favoriting (revisit?)
