### ISSUE TITLE
Read Only Migration

### ISSUE THREAD

**Issue by jamesturk** [openstates/planning#6]
In the immediate future we need OpenStates.org running on non-Sunlight servers.
- [x] OpenStates.org app server
- [x] MongoDB server
- [x] FTS solution
- [x] Geo Solution
- [x] update OpenStates.org to remove stale contact references/etc.
- [ ] update OpenStates API docs to note coming changes

**Comment by mileswwatkins** [comment]
This is all pretty much done, right? (Save for full updating of the docs, outside of just the API key bits.)

**Comment by jamesturk** [comment]
yeah, the FTS solution is temporary, I'll make a separate ticket for migrating it to a new system

**Comment by jamesturk** [comment]
closing this one out in favor of the more detailed tickets
